Merge #6637: build: merge bitcoin#28092, #28999, #27872, #29486, #25972 (ensure `WARN_CXXFLAGS` are populated to ensure expected `--enable-werror` behavior)
af14f233a55d290cacb4d0a5aba325e0383b04bc ci: don't build using `-Werror` when using Clang (Kittywhiskers Van Gogh)
3b837c8d16084fde6d025fe5a3ad75b08c55ed56 ci: don't build using `-Werror` when using GCC (Kittywhiskers Van Gogh)
04e036e99eb49d7a1e51968923dd97741456c583 revert: make fuzzing builds stricter by enabling -Werror by default (Kittywhiskers Van Gogh)
29090a045925bdcdae114cfbaf6fccdfd7ff00d1 merge bitcoin#25972: no-longer disable WARN_CXXFLAGS when CXXFLAGS is set (Kittywhiskers Van Gogh)
d0548f8b1c51475c67e2b2cf0e2e46cd23405bc3 merge bitcoin#29486: remove -Wdocumentation conditional (Kittywhiskers Van Gogh)
0f4812f4d089422d47820430e4c1689a1571fb61 merge bitcoin#27872: suppress external warnings by default (Kittywhiskers Van Gogh)
71007801e8dfd1f793b782533f7b84b80df84e2c merge bitcoin#28999: Enable -Wunreachable-code (Kittywhiskers Van Gogh)
5471c58319a38435227d9efc6a680d3c57c31ef7 merge bitcoin#28092: document that -Wreturn-type has been fixed upstream (mingw-w64) (Kittywhiskers Van Gogh)
9098c9cc1101049269ff0586a146bf6069317f85 build: always enable -Wsuggest-override (Kittywhiskers Van Gogh)

Pull request description:

  ## Motivation

  While working on [dash#6633](https://github.com/dashpay/dash/pull/6633), I had built `develop` (5e4a8927a4a35a3c7e352915cdeb3ac1fb30d4da) but the build _failed_ locally due to a `-Wthread-safety` warning (see below) that was introduced by [bitcoin#25337](https://github.com/bitcoin/bitcoin/pull/25337) ([commit](https://github.com/dashpay/dash/commit/a7d4127ea87c64d7015c7650c60025f4758fdbe4)). It was caught because I use additional `CXXFLAGS` on my local system but it _should_ have been caught by CI, especially since [bitcoin#20182](https://github.com/bitcoin/bitcoin/pull/20182) ([commit](https://github.com/dashpay/dash/commit/14a67ee85edb2a38d23658e4d9c103d11d87f154)) made `--enable-werror` the default for CI and the sole exception (the Windows build) was remedied with [bitcoin#20586](https://github.com/bitcoin/bitcoin/pull/20586) ([commit](https://github.com/dashpay/dash/commit/750447e345d9f3fcae3d8a63fe7baac5224bfac0)), so every build variant should've run with `-Werror`.

  <details>

  <summary>Compile error:</summary>

  ```
    CXX      wallet/libbitcoin_wallet_a-sqlite.o
  wallet/rpcwallet.cpp:1038:36: error: calling function 'IsMine' requires holding mutex 'wallet.cs_wallet' exclusively [-Werror,-Wthread-safety-analysis]
   1038 |         isminefilter mine = wallet.IsMine(address);
        |                                    ^
  ```

  </details>

  But that didn't happen. Till [bitcoin#23149](https://github.com/dashpay/dash/commit/70ed6b47f952bacd37d69a39c6fe122e7668cb49), there were a separate set of warnings (overridable by `CXXFLAGS`) and errors (overridable by `CXXFLAG_WERROR`). _Before_ the backport, coverage was as expected ([build](https://gitlab.com/dashpay/dash/-/jobs/9221165750#L786), search for `-Werror=thread-safety`) but _after_ the backport, `thread-safety` (and other expected warnings) were no longer being evaluated ([build](https://gitlab.com/dashpay/dash/-/jobs/9238308844#L740), search for `-Werror` and `-Wthread-safety`, only the former is present).

  Expected `CXXFLAGS`:

  ```
  CXXFLAGS            =  -O0 -g3 -ftrapv -fdebug-prefix-map=$(abs_top_srcdir)=. -Wall -Wextra -Wgnu -Wformat
                         -Wformat-security -Wreorder -Wvla -Wshadow-field -Wthread-safety -Wloop-analysis
                         -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized
                         -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment
                         -Wimplicit-fallthrough -Wno-unused-parameter -Wno-self-assign -Werror
                         -pipe -std=c++20 -O2 -O0 -g0
  ```

  Actual `CXXFLAGS`:

  ```
  CXXFLAGS            =  -O0 -g3 -ftrapv -fdebug-prefix-map=$(abs_top_srcdir)=. -Werror -pipe -std=c++20 -O2 -O0 -g0
  ```

  This happened because `CXXFLAGS` are overridden by default which results in none of the warnings making it to the final `CXXFLAGS`, which reduced the effectiveness of `-Werror` substantially (while `CXXFLAG_WERROR` was left undisturbed, which allowed pre-backport builds to include coverage). This is remedied by backporting [bitcoin#25972](https://github.com/bitcoin/bitcoin/pull/25972) (done by this PR), which will ensure that `WARN_CXXFLAGS` are included _even if `CXXFLAGS` are overridden_ and is possible because [bitcoin#24391](https://github.com/bitcoin/bitcoin/pull/24391) ([commit](https://github.com/dashpay/dash/commit/11323c38511f1e5b8e1a8154124f736628db6b76)) is already in `develop`.

  ## Additional Information

  * Dependency for https://github.com/dashpay/dash/pull/6638

  * Dependency for https://github.com/dashpay/dash/pull/6639

  * Because the warnings (converted to errors with `-Werror`) cast a wider net than the older set of error flags, `develop` in its current state does not compile. To allow CI to bless this PR, `-Werror` for both Clang and GCC-based builds have been  **tentatively** disabled and will be re-enabled by the dependent PRs listed above.

    It is recommended to read the pull request description for both dependents while reviewing this PR.

  * `-Wsuggest-override` was made unconditional in [bitcoin#28348](https://github.com/bitcoin/bitcoin/pull/28348) ([commit](https://github.com/dashpay/dash/commit/c71e3df8b48db29a860c5b7207e663435909ebd2)) **but** there were two such conditional checks, they were deduplicated in [bitcoin#23149](https://github.com/bitcoin/bitcoin/pull/23149) but the former was merged before the latter (i.e. out-of-order) and one conditional check lingered around. This lingering check has been removed as we don't support GCC 9.2.

  * `CXXFLAGS` set for the fuzz build ([commit](https://github.com/dashpay/dash/commit/184bd6031ba10b9a5defdaa6512a8ab832f169ac)) that enabled `-Werror` are made redundant with [bitcoin#20182](https://github.com/bitcoin/bitcoin/pull/20182) and therefore, have been removed.

  ## Breaking Changes

  None expected.

  ## Checklist

  - [x] I have performed a self-review of my own code
  - [x] I have commented my code, particularly in hard-to-understand areas **(note: N/A)**
  - [x] I have added or updated relevant unit/integration/functional/e2e tests **(note: N/A)**
  - [x] I have made corresponding changes to the documentation
  - [x] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

ACKs for top commit:
  UdjinM6:
    utACK af14f233a55d290cacb4d0a5aba325e0383b04bc

Tree-SHA512: ccdaf71cf79eb3aec2468c4c1eaa696cd120c03e9665a3c4b56da6ef17cca9585ef8c66ac1625f2ba243c7f80f15e92a336c0bd90b5f11969fabb3adde3c8125